#!/usr/bin/env python3
import argparse
from sys import stderr
from serie_parser.serie_parser import Serie, Parser
from gui.gui import TelemetryGUI
from PyQt6.QtWidgets import QApplication
import pyqtgraph as pg


def display_plots(name: str, timestamp: int, series: dict[int:Serie]):
    app = QApplication([])
    viewer = TelemetryGUI(name, timestamp, series.values())
    viewer.show()
    app.exec()
    return


def parse_arguments():
    parser = argparse.ArgumentParser(
        prog="telemetry_viewer",
        description="A visualizer for telemetry files.",
    )
    parser.add_argument(
        "FILE",
        metavar="FILE",
        type=str,
        help="File to analyze.",
    )
    args = parser.parse_args()

    return args


def main_viewer(file: str) -> int:
    name: str = "default"
    timestamp: int = 0
    series: dict[int:Serie] = {}
    try:
        with open(file, 'rb') as file_content:
            parsed = Parser(file_content.read())
            name, timestamp, series = parsed.get_datas()
    except Exception as err:
        print(str(err))
        raise FileNotFoundError(
            f"Failed to load values from file '{file}'") from err

    print(f"Telemetry infos from file '{file}' properly loaded.")
    print(name, timestamp)
    for _, serie in series.items():
        print(serie)
        serie.print_values()
    display_plots(name, timestamp, series)
    return 0


if __name__ == "__main__":
    try:
        arg = parse_arguments()
        main_viewer(arg.FILE)
    except Exception as e:
        print(e, file=stderr)
        exit(1)
